name: Semgrep

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    permissions:
      security-events: write
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install semgrep
        run: |
          python3 -m pip install semgrep

      - name: Run semgrep
        run: |
          semgrep ci --config rules --sarif --sarif-output=semgrep.sarif src

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep
